scrape_configs:
  - job_name: 'Kafka Consumer Input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:5658']
        labels:
          application: 'Wikimedia Consumer'